# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('data_birth', models.DateField(blank=True, null=True, verbose_name='Када радилси?')),
                ('course', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Spisok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='instructors',
            name='who_i_am_s',
            field=models.ManyToManyField(to='instructor.Spisok'),
        ),
    ]
