# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='data_birth',
            field=models.DateField(null=True, verbose_name='Када радилси?'),
        ),
    ]
