# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructors_data_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='data_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Када радилси?'),
        ),
    ]
