# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_auto_20171013_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spisok_vibora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='Имя элемента выбора')),
            ],
        ),
        migrations.AddField(
            model_name='instructors',
            name='who_i_am',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructor.Spisok_vibora'),
            preserve_default=False,
        ),
    ]
