# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20171013_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisok_vibora',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
