# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_auto_20171013_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spisok_vibora',
            new_name='Spisok',
        ),
    ]
