# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товары в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.AddField(
            model_name='order',
            name='customer_adress',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='numb',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
        ),
    ]
