# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171103_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='prouct',
            new_name='product',
        ),
    ]
