# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Представление товара, наименование')),
                ('description', models.CharField(blank=True, max_length=600, verbose_name='Описание товара')),
                ('number', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='Остаток товара')),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=1000, max_digits=10, verbose_name='Цена товара')),
                ('first_foto', models.ImageField(blank=True, max_length=900, upload_to='foto/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spisok_foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(max_length=900, upload_to='foto/')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
            options={
                'verbose_name': 'Фотографии товаров',
                'verbose_name_plural': 'Фотографии товаров',
            },
        ),
    ]
