# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171103_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Цена товара'),
        ),
    ]
