# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, verbose_name='Скидка'),
        ),
    ]
